name: Update
on:
  schedule:
    - cron: '0 12-23/2 * * *'
  workflow_dispatch:
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: sync
        run: |
          curl -s https://https://${{ secrets.BOT_TOKEN }}@raw.githubusercontent.com/sociedatos/hospitalizados-bolivia/main/data/internaciones.departamentos.csv > hospitalizados_por_departamento.csv
      - name: commit
        run: |
          git config --global user.email "mauriforonda+socialdatos@gmail.com"
          git config --global user.name "sociedatosbot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualización"; git push -q "https://${{ secrets.BOT_TOKEN }}@github.com/sociedatos/bo-hospitalizados_por_departamento.git" master)
